# Generated by Django 6.0.1 on 2026-01-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_wellnessclass_day_of_week_wellnessclass_is_recurring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_type',
            field=models.CharField(choices=[('drop_in', 'Drop-in'), ('prepaid', 'Pre-paid (Discounted)')], default='drop_in', max_length=20),
        ),
    ]
