# Generated by Django 6.0.1 on 2026-01-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_booking_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellnessclass',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
