# Generated by Django 6.0.1 on 2026-01-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_wellnessclass_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_proof',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
