# Generated by Django 6.0.1 on 2026-01-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_booking_payment_proof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='preference_tag',
        ),
        migrations.AddField(
            model_name='booking',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
