# Generated by Django 6.0.1 on 2026-01-30 08:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_remove_booking_preference_tag_booking_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellnessclass',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
