# Generated by Django 6.0.1 on 2026-01-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_wellnessclass_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellnessclass',
            name='description',
            field=models.TextField(default='No description provided'),
            preserve_default=False,
        ),
    ]
