# Generated by Django 6.0.1 on 2026-03-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0012_booking_note_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='adjustment_preference',
            field=models.CharField(blank=True, choices=[('ask_each_class', 'Ask each class'), ('verbal_only', 'Verbal only'), ('hands_off', 'Hands-off')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='consent_share_health_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instructor_notes',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='intensity_preference',
            field=models.CharField(blank=True, choices=[('gentle', 'Gentle'), ('moderate', 'Moderate'), ('dynamic', 'Dynamic')], max_length=12),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='long_term_conditions',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='movement_limitations',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='practice_goal',
            field=models.CharField(blank=True, choices=[('stress_relief', 'Stress relief'), ('mobility', 'Mobility'), ('strength', 'Strength'), ('pain_management', 'Pain management'), ('recovery', 'Recovery')], max_length=20),
        ),
    ]
